name: GitLeaks Secret Scan

on:
  pull_request:
    branches:
      - main

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GitLeaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --redact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
