name: Secret Scan on PR

on:
  pull_request:
    branches:
      - main

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Gitleaks CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/zricethezav/gitleaks/main/install.sh | bash

      - name: Run Gitleaks scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Scan the current code and fail if secrets found
          gitleaks detect --source=. --verbose --redact
