name: Secret Scan on PR

on:
  pull_request:
    branches:
      - main

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Checkout the PR branch

      - name: Run GitLeaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   # Required for scanning PRs
          args: --verbose

      - name: Fail if secrets found
        if: failure()
        run: |
          echo "Secrets detected! Please fix before merging."
          exit 1
